USE [Flashcards]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Description] [varchar](500) NULL,
	[Color] [nchar](6) NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Deck](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Deck] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Deck_Flashcard](
	[DeckId] [int] NOT NULL,
	[FlashcardId] [int] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Flashcard](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[Front] [varchar](500) NOT NULL,
	[Back] [varchar](500) NOT NULL,
	[CategoryId] [int] NOT NULL,
 CONSTRAINT [PK_Flashcard] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Deck_Flashcard]  WITH CHECK ADD  CONSTRAINT [FK_Deck_Flashcard_Deck] FOREIGN KEY([DeckId])
REFERENCES [dbo].[Deck] ([Id])
GO
ALTER TABLE [dbo].[Deck_Flashcard] CHECK CONSTRAINT [FK_Deck_Flashcard_Deck]
GO
ALTER TABLE [dbo].[Deck_Flashcard]  WITH CHECK ADD  CONSTRAINT [FK_Deck_Flashcard_Flashcard] FOREIGN KEY([FlashcardId])
REFERENCES [dbo].[Flashcard] ([Id])
GO
ALTER TABLE [dbo].[Deck_Flashcard] CHECK CONSTRAINT [FK_Deck_Flashcard_Flashcard]
GO
ALTER TABLE [dbo].[Flashcard]  WITH CHECK ADD  CONSTRAINT [FK_Flashcard_Category] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([Id])
GO
ALTER TABLE [dbo].[Flashcard] CHECK CONSTRAINT [FK_Flashcard_Category]
GO
